spring:
  application:
    name: server
  sql:
    init:
      mode: always
  datasource:
    url: 'jdbc:mysql://localhost:3306/pixapencil'
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-southeast-2
logging:
  level:
    org:
      springframework:
        security: DEBUG
